# Generated by Django 2.0.7 on 2019-01-31 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealtchCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('U', 'Users'), ('A', 'Agency'), ('G', 'Group')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='HealthCheckCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=50)),
                ('operator', models.CharField(choices=[('=', '='), ('include', 'include')], max_length=20)),
                ('value', models.CharField(max_length=30)),
                ('level', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='healtchcheck',
            name='failed_if',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='run_checks.HealthCheckCondition'),
        ),
        migrations.AddField(
            model_name='healtchcheck',
            name='when',
            field=models.ManyToManyField(related_name='all_conditions', to='run_checks.HealthCheckCondition'),
        ),
    ]
