# Generated by Django 2.1.5 on 2019-01-31 15:33

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('location_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('start_date', models.DateField(auto_now_add=True, null=True)),
                ('end_date', models.DateField(null=True)),
                ('licenses', djongo.models.fields.ListField(null=True, verbose_name=models.CharField(max_length=30))),
                ('agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agency_users.Agency')),
            ],
        ),
    ]
