# Generated by Django 2.0.7 on 2019-01-31 03:50

import agency_users.models
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('location_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('license', djongo.models.fields.ArrayModelField(model_container=agency_users.models.License)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency_users.Agency')),
            ],
        ),
    ]
